[package]
name = "evm-gasometer"
version = "0.17.0"
license = "Apache-2.0"
authors = ["Wei Tang <hi@that.world>", "Parity Technologies <admin@parity.io>"]
description = "Portable Ethereum Virtual Machine implementation written in pure Rust."
repository = "https://github.com/sorpaas/rust-evm"
keywords = ["no_std", "ethereum"]
edition = "2018"

[dependencies]
primitive-types = { version = "0.9.1", default-features = false }
evm-core = { version = "0.17", path = "../core", default-features = false }
evm-runtime = { version = "0.17", path = "../runtime", default-features = false }

[features]
default = ["std"]
std = [
  "evm-core/std",
  "evm-runtime/std",
  "primitive-types/std",
]
